### ISSUE TITLE
Variable hoisting cause unpredictable postProcess behaviors

### ISSUE THREAD

**Issue by ghostoy** [augustl/js-epub#4]
postProcess: function () {
        for (var key in this.opf.manifest) {
            var mediaType = this.opf.manifest[key]["media-type"]
            var href = this.opf.manifest[key]["href"]
            var result = undefined;   // "result" is hoisted, so it must be initialize to undefined explicitly

            if (mediaType === "text/css") {
                result = this.postProcessCSS(href);
            } else if (mediaType === "application/xhtml+xml") {
                result = this.postProcessHTML(href);
            }

            if (result !== undefined) {
                this.files[href] = result;
            }
        }
    }

**Comment by augustl** [comment]
I just deprecated this project. A much better alternative exists now, that wasn't around when I originally created the project. Check it out :) https://github.com/futurepress/epub.js/
