### ISSUE TITLE
TypeError: 'undefined' is not an object (evaluating 'c.getElementsByTagName("rootfile")[0].getAttribute')

### ISSUE THREAD

**Issue by mebibou** [augustl/js-epub#5]
Hey there,
it seems like a very nice library. However, whenever I try to read a file from a servlet written in Java, I get the following error (Safari 5.1.2/Chrome 16.0.912.77):
TypeError: 'undefined' is not an object (evaluating 'c.getElementsByTagName("rootfile")[0].getAttribute')

I have tried with Base64 encoding, without, but it still gives me the same error. What do you think could be the problem?

Thanks!

**Comment by augustl** [comment]
I just deprecated this project. A much better alternative exists now, that wasn't around when I originally created the project. Check it out :) https://github.com/futurepress/epub.js/
